@startuml mobile
start
title Додавання товару в список
repeat
:Отримання id товару;
:Запит до БД;
if(Чи існує такий id?) then (ні)
:Отримання даних товару (назва, ціна, кількість);
:Запис в БД;
break
else (так)
:Вивід такий id вже існує;
endif
repeat while (Ввести новий id) is (так) not (ні)

stop
@enduml