start
title Процес редагування товару в БД
repeat
:Ввід id страви;
:Вивід повної інформації про страву;
:Вибір критеріїв редагування;
fork
    :Назва товару;
fork again
    :Категорія товару;
fork again
    :Ціна товару;
end fork    
if(Підтвердити редагування?) then (так)
:З'єднання з сервером;
:Відправка запиту на сервер;
:Редагування даних в БД;
break
else(ні)
endif
repeat while (Редагувати інший товар) is (так) not (ні)
stop 