start
title Процес авторизації адміна
repeat
:Ввід логіну і паролю;
:Вивід повної інформації про страву;
:З'єднання з сервером;
:Відправка запиту на сервер;
while (Авторизація успішна?) is (так)
:Вивід "Авторизація успішна";
stop
endwhile(ні)
 