start
title Процес видалення товару з БД
repeat
:Ввід id страви;
:Вивід повної інформації про страву;
if(Підтвердити видалення?) then (так)
:З'єднання з сервером;
:Відправка запиту на сервер;
:Видалення з бд БД;
break
else(ні)
endif
repeat while (Видалити інший товар) is (так) not (ні)
stop 