start
title Процес оформлення та оплати замовлення

:Вивід даних замовлення;
if (Замовлення коректне?) then (так)
 repeat
 :Вивід даних щодо оплати;
    if(Оплата успішна?) then (так)
     :Запис в БД та відправка на опрацювання;
     :Вивід "Оплата успіша " та номер замовлення;
     break

    else(ні)
     :Вивід "Помилка оплати";
     endif
 repeat while (Спробувати ще раз?) is (так) not (ні)
   
else(ні) 
 if(Повернутись до вибору товарів?) then (так)
 :Повернутись до меню вибору товарів;
 else(ні)
 :Скасувати замовлення;
 endif
endif
stop