start
title Процес вибору страви
repeat
:Вибір продукту;
:Вибір кількості;
:Відправка запиту на сервер;
if(З'єднання з сервером успішне) then (так)
    if (Перевірка наявності товару) then (Так) 
    :Запис до замовлення;
    
    else(Ні)
    :Вивід повідомлення 
    про відсутність товару;
    endif

else(ні)
 
 stop
endif
repeat while (Перейти до оплати?) is (ні) not (так)

stop

 