start
title Процес вибору замовлення персоналом
:Вивід наявних замовлень;
:Ввід айді замовлення для опраювання;
:З'єднання з сервером;
:Відправка запиту на сервер;
:Позначення замовлення в БД як "в роботі";
stop
