start
title Процес підтвердження або скасування виконання замовлення
:Вибір дії для замовлення;
if(Замовлення) then (підтвердити)
:З'єднання з сервером;
:Відправка запиту на сервер;
:Позначення замовлення в БД як "виконано";
else (відмінити)
:З'єднання з сервером;
:Відправка запиту на сервер;
:Позначення замовлення в БД як "не виконане";
endif
stop